// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RS.EF;

#nullable disable

namespace RS.EF.Data.Migrations
{
    [DbContext(typeof(RSDBContext))]
    partial class RSDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RS.COMMON.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyScaleId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyWorkLineId")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyScaleId");

                    b.HasIndex("CompanyTypeId");

                    b.HasIndex("CompanyWorkLineId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("RS.COMMON.Entities.CompanyOutsourceCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("OutsourceCompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("OutsourceCompanyId");

                    b.ToTable("CompanyOutsourceCompany");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.CompanyScale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyScale");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.CompanyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyType");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.CompanyWorkLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyWorkLine");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.Corporation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<int?>("CorporationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CorporationTypeId");

                    b.ToTable("Corporation");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.CorporationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CorporationType");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("District");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.EmployeeCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeCount");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.EmploymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmploymentType");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gender");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.InterventionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InterventionType");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.ProtestoEmployeeCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProtestoEmployeeCount");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.ProtestoPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProtestoPlace");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.ProtestoType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AgainstProduction")
                        .HasColumnType("bit");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Simple")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ProtestoType");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.ResistanceReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResistanceReason");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.TradeUnion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TradeUnionConfederationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TradeUnionConfederationId");

                    b.ToTable("TradeUnion");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.TradeUnionAuthority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TradeUnionAuthority");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.TradeUnionConfederation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TradeUnionConfederation");
                });

            modelBuilder.Entity("RS.COMMON.Entities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("RS.COMMON.Entities.Protesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustodyCount")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("EmployeeCountNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProtestoEmployeeCountId")
                        .HasColumnType("int");

                    b.Property<int>("ResistanceId")
                        .HasColumnType("int");

                    b.Property<string>("SimpleProtestoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StrikeDuration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("ProtestoEmployeeCountId");

                    b.HasIndex("ResistanceId");

                    b.ToTable("Protesto");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ProtestoCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("ProtestoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ProtestoId");

                    b.ToTable("ProtestoCity");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ProtestoDistrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("ProtestoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProtestoId");

                    b.ToTable("ProtestoDistrict");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ProtestoInterventionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterventionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ProtestoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterventionTypeId");

                    b.HasIndex("ProtestoId");

                    b.ToTable("ProtestoInterventionType");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ProtestoLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProtestoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("ProtestoId");

                    b.ToTable("ProtestoLocation");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ProtestoProtestoPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProtestoId")
                        .HasColumnType("int");

                    b.Property<int>("ProtestoPlaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProtestoId");

                    b.HasIndex("ProtestoPlaceId");

                    b.ToTable("ProtestoProtestoPlace");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ProtestoProtestoType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProtestoId")
                        .HasColumnType("int");

                    b.Property<int>("ProtestoTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProtestoId");

                    b.HasIndex("ProtestoTypeId");

                    b.ToTable("ProtestoProtestoType");
                });

            modelBuilder.Entity("RS.COMMON.Entities.Resistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AnyLegalIntervention")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("CorporationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DevelopRight")
                        .HasColumnType("bit");

                    b.Property<int?>("EmployeeCountId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeCountNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FiredEmployeeCountByProtesto")
                        .HasColumnType("int");

                    b.Property<bool>("HasTradeUnion")
                        .HasColumnType("bit");

                    b.Property<string>("LegalInterventionDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MainCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResistanceResult")
                        .HasColumnType("int");

                    b.Property<int>("ResistanceTargetType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TradeUnionAuthorityId")
                        .HasColumnType("int");

                    b.Property<int?>("TradeUnionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updater")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CorporationId");

                    b.HasIndex("EmployeeCountId");

                    b.HasIndex("MainCompanyId");

                    b.HasIndex("TradeUnionAuthorityId");

                    b.HasIndex("TradeUnionId");

                    b.ToTable("Resistance");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ResistanceCorporation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorporationId")
                        .HasColumnType("int");

                    b.Property<int>("ResistanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorporationId");

                    b.HasIndex("ResistanceId");

                    b.ToTable("ResistanceCorporation");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ResistanceEmploymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmploymentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ResistanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmploymentTypeId");

                    b.HasIndex("ResistanceId");

                    b.ToTable("ResistanceEmploymentType");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ResistanceNews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NewsId")
                        .HasColumnType("int");

                    b.Property<int>("ResistanceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.HasIndex("ResistanceId");

                    b.ToTable("ResistanceNews");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ResistanceResistanceReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ResistanceId")
                        .HasColumnType("int");

                    b.Property<int>("ResistanceReasonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResistanceId");

                    b.HasIndex("ResistanceReasonId");

                    b.ToTable("ResistanceResistanceReason");
                });

            modelBuilder.Entity("RS.COMMON.Entities.Company", b =>
                {
                    b.HasOne("RS.COMMON.Entities.LookupEntity.CompanyScale", "CompanyScale")
                        .WithMany()
                        .HasForeignKey("CompanyScaleId");

                    b.HasOne("RS.COMMON.Entities.LookupEntity.CompanyType", "CompanyType")
                        .WithMany()
                        .HasForeignKey("CompanyTypeId");

                    b.HasOne("RS.COMMON.Entities.LookupEntity.CompanyWorkLine", "CompanyWorkLine")
                        .WithMany()
                        .HasForeignKey("CompanyWorkLineId");

                    b.Navigation("CompanyScale");

                    b.Navigation("CompanyType");

                    b.Navigation("CompanyWorkLine");
                });

            modelBuilder.Entity("RS.COMMON.Entities.CompanyOutsourceCompany", b =>
                {
                    b.HasOne("RS.COMMON.Entities.Company", "Company")
                        .WithMany("OutsourceCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RS.COMMON.Entities.Company", "OutsourceCompany")
                        .WithMany()
                        .HasForeignKey("OutsourceCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("OutsourceCompany");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.Corporation", b =>
                {
                    b.HasOne("RS.COMMON.Entities.LookupEntity.CorporationType", "CorporationType")
                        .WithMany()
                        .HasForeignKey("CorporationTypeId");

                    b.Navigation("CorporationType");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.District", b =>
                {
                    b.HasOne("RS.COMMON.Entities.LookupEntity.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("RS.COMMON.Entities.LookupEntity.TradeUnion", b =>
                {
                    b.HasOne("RS.COMMON.Entities.LookupEntity.TradeUnionConfederation", "TradeUnionConfederation")
                        .WithMany()
                        .HasForeignKey("TradeUnionConfederationId");

                    b.Navigation("TradeUnionConfederation");
                });

            modelBuilder.Entity("RS.COMMON.Entities.Protesto", b =>
                {
                    b.HasOne("RS.COMMON.Entities.LookupEntity.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RS.COMMON.Entities.LookupEntity.ProtestoEmployeeCount", "ProtestoEmployeeCount")
                        .WithMany()
                        .HasForeignKey("ProtestoEmployeeCountId");

                    b.HasOne("RS.COMMON.Entities.Resistance", "Resistance")
                        .WithMany("Protestos")
                        .HasForeignKey("ResistanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("ProtestoEmployeeCount");

                    b.Navigation("Resistance");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ProtestoCity", b =>
                {
                    b.HasOne("RS.COMMON.Entities.LookupEntity.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RS.COMMON.Entities.Protesto", "Protesto")
                        .WithMany("Cities")
                        .HasForeignKey("ProtestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Protesto");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ProtestoDistrict", b =>
                {
                    b.HasOne("RS.COMMON.Entities.LookupEntity.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RS.COMMON.Entities.Protesto", "Protesto")
                        .WithMany("Districts")
                        .HasForeignKey("ProtestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Protesto");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ProtestoInterventionType", b =>
                {
                    b.HasOne("RS.COMMON.Entities.LookupEntity.InterventionType", "InterventionType")
                        .WithMany()
                        .HasForeignKey("InterventionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RS.COMMON.Entities.Protesto", "Protesto")
                        .WithMany("ProtestoInterventionTypes")
                        .HasForeignKey("ProtestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterventionType");

                    b.Navigation("Protesto");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ProtestoLocation", b =>
                {
                    b.HasOne("RS.COMMON.Entities.LookupEntity.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RS.COMMON.Entities.LookupEntity.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("RS.COMMON.Entities.Protesto", "Protesto")
                        .WithMany("Locations")
                        .HasForeignKey("ProtestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("District");

                    b.Navigation("Protesto");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ProtestoProtestoPlace", b =>
                {
                    b.HasOne("RS.COMMON.Entities.Protesto", "Protesto")
                        .WithMany("ProtestoProtestoPlaces")
                        .HasForeignKey("ProtestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RS.COMMON.Entities.LookupEntity.ProtestoPlace", "ProtestoPlace")
                        .WithMany()
                        .HasForeignKey("ProtestoPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protesto");

                    b.Navigation("ProtestoPlace");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ProtestoProtestoType", b =>
                {
                    b.HasOne("RS.COMMON.Entities.Protesto", "Protesto")
                        .WithMany("ProtestoProtestoTypes")
                        .HasForeignKey("ProtestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RS.COMMON.Entities.LookupEntity.ProtestoType", "ProtestoType")
                        .WithMany()
                        .HasForeignKey("ProtestoTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protesto");

                    b.Navigation("ProtestoType");
                });

            modelBuilder.Entity("RS.COMMON.Entities.Resistance", b =>
                {
                    b.HasOne("RS.COMMON.Entities.LookupEntity.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RS.COMMON.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("RS.COMMON.Entities.LookupEntity.Corporation", "Corporation")
                        .WithMany()
                        .HasForeignKey("CorporationId");

                    b.HasOne("RS.COMMON.Entities.LookupEntity.EmployeeCount", "EmployeeCount")
                        .WithMany()
                        .HasForeignKey("EmployeeCountId");

                    b.HasOne("RS.COMMON.Entities.Company", "MainCompany")
                        .WithMany()
                        .HasForeignKey("MainCompanyId");

                    b.HasOne("RS.COMMON.Entities.LookupEntity.TradeUnionAuthority", "TradeUnionAuthority")
                        .WithMany()
                        .HasForeignKey("TradeUnionAuthorityId");

                    b.HasOne("RS.COMMON.Entities.LookupEntity.Corporation", "TradeUnion")
                        .WithMany()
                        .HasForeignKey("TradeUnionId");

                    b.Navigation("Category");

                    b.Navigation("Company");

                    b.Navigation("Corporation");

                    b.Navigation("EmployeeCount");

                    b.Navigation("MainCompany");

                    b.Navigation("TradeUnion");

                    b.Navigation("TradeUnionAuthority");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ResistanceCorporation", b =>
                {
                    b.HasOne("RS.COMMON.Entities.LookupEntity.Corporation", "Corporation")
                        .WithMany()
                        .HasForeignKey("CorporationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RS.COMMON.Entities.Resistance", "Resistance")
                        .WithMany("ResistanceCorporations")
                        .HasForeignKey("ResistanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corporation");

                    b.Navigation("Resistance");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ResistanceEmploymentType", b =>
                {
                    b.HasOne("RS.COMMON.Entities.LookupEntity.EmploymentType", "EmploymentType")
                        .WithMany()
                        .HasForeignKey("EmploymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RS.COMMON.Entities.Resistance", "Resistance")
                        .WithMany("ResistanceEmploymentTypes")
                        .HasForeignKey("ResistanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmploymentType");

                    b.Navigation("Resistance");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ResistanceNews", b =>
                {
                    b.HasOne("RS.COMMON.Entities.News", "News")
                        .WithMany()
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RS.COMMON.Entities.Resistance", "Resistance")
                        .WithMany("ResistanceNews")
                        .HasForeignKey("ResistanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");

                    b.Navigation("Resistance");
                });

            modelBuilder.Entity("RS.COMMON.Entities.ResistanceResistanceReason", b =>
                {
                    b.HasOne("RS.COMMON.Entities.Resistance", "Resistance")
                        .WithMany("ResistanceResistanceReasons")
                        .HasForeignKey("ResistanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RS.COMMON.Entities.LookupEntity.ResistanceReason", "ResistanceReason")
                        .WithMany()
                        .HasForeignKey("ResistanceReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resistance");

                    b.Navigation("ResistanceReason");
                });

            modelBuilder.Entity("RS.COMMON.Entities.Company", b =>
                {
                    b.Navigation("OutsourceCompanies");
                });

            modelBuilder.Entity("RS.COMMON.Entities.Protesto", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Districts");

                    b.Navigation("Locations");

                    b.Navigation("ProtestoInterventionTypes");

                    b.Navigation("ProtestoProtestoPlaces");

                    b.Navigation("ProtestoProtestoTypes");
                });

            modelBuilder.Entity("RS.COMMON.Entities.Resistance", b =>
                {
                    b.Navigation("Protestos");

                    b.Navigation("ResistanceCorporations");

                    b.Navigation("ResistanceEmploymentTypes");

                    b.Navigation("ResistanceNews");

                    b.Navigation("ResistanceResistanceReasons");
                });
#pragma warning restore 612, 618
        }
    }
}
