// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using RS.EF;
using System;

namespace RS.EF.Data.Migrations
{
    [DbContext(typeof(RSDBContext))]
    partial class RSDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("RS.COMMON.Entities.Resistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id")
                        .HasName("PrimaryKey_ResistanceId");

                    b.ToTable("Resistance");
                });
#pragma warning restore 612, 618
        }
    }
}
